import { IconDefinition } from '@fortawesome/angular-fontawesome';
import {
  faHouse,
  faDatabase,
  faUsers,
  faFileImport,
  faBuilding,
  faBullseye,
  faKey,
  faArrowRight,
  faArrowLeft,
  faEllipsisVertical,
  faCircleExclamation,
  faShip,
  faShieldHalved,
  faUserShield,
  faUmbrella,
  faCircleCheck,
  faCircleUp,
  faCircleDown,
  faRocket,
  faPaperclip,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons: IconDefinition[] = [
  faHouse,
  faDatabase,
  faUsers,
  faFileImport,
  faBuilding,
  faBullseye,
  faKey,
  faArrowRight,
  faArrowLeft,
  faEllipsisVertical,
  faCircleExclamation,
  faShip,
  faShieldHalved,
  faUserShield,
  faUmbrella,
  faCircleCheck,
  faCircleUp,
  faCircleDown,
  faRocket,
  faPaperclip,
];
